export const customerinitValueForm = {
    fullname: '',
    gender: '',
    street: '',
    streetNr: '',
    zipCode: '',
    city: '',
    country: '',
    email: '',
    phone: '',
    fax: '',
    hasCruise: '',
    citizenship: '',
    residencePermit: '',
    occupation: '',
    destinationCountry: '',
    kindOfVisa: '30 Days Tourist Single Entry',
    travelStartDate: '2016-05-15',
    returnFlightDate: '2016-05-15',
    arrivalSameasDepartureAirport: '',
    invoiceRecipientSameAsApplicant: '',
    entireTravelInUAE: '',
    place: '',
    date: '',
    signature: '',
};
