export const customerInitValueForm = {
  selectedCountry: '',
  visaType: '',
  fullname: '',
  gender: 'male',
  street: '',
  streetNr: '',
  zipCode: '',
  city: '',
  country: '',
  email: '',
  phone: '',
  fax: '',
  hasCruise: 'yes',
  citizenship: '',
  // residencePermit: '',
  occupation: '',
  destinationCountry: '',
  kindOfVisa: '30 Days Tourist Single Entry',
  travelStartDate: '',
  returnFlightDate: '',
  arrivalSameasDepartureAirport: 'yes',
  invoiceRecipientSameAsApplicant: 'yes',
  entireTravelInUAE: 'yes',
  place: '',
  dateOfSignature: '',
  signature: '',
  passportImage: '',
  residencePermitImage: '',
};
